#!/bin/sh

# GPIO numbers should be from this list
# 0, 1, 4, 7, 8, 9, 10, 11, 14, 15, 17, 18, 21, 22, 23, 24, 25

# Note that the GPIO numbers that you program here refer to the pins
# of the BCM2835 and *not* the numbers on the pin header.
# So, if you want to activate GPIO7 on the header you should be
# using GPIO4 in this script. Likewise if you want to activate GPIO0
# on the header you should be using GPIO17 here.

/usr/local/bin/gpio  export 27 out

/usr/local/bin/gpio  export 22 in

/usr/local/bin/gpio  export 12 out

/usr/local/bin/gpio  export 8 out

/usr/local/bin/gpio  export 10 out

/usr/local/bin/gpio  export 9 in

/usr/local/bin/gpio  export 11 out
